#Config file
options:
  sheep:
    dropMutton: true
  creeper:
    dropMobHead: true
  worlds: [world]

modify:
  blocks:
    namespace:
      block_id: true
  items:
    namespace:
      item_id: true
    
protocollib:
  blocks:
    actual_block: what_you_wanna_replace_it_with
  items:
    #dont forget to put the blocks here too, as all blocks have an item form
    actual_item: what_you_wanna_replace_it_with
    
features:
  monsterEggMobSpawner: true
    
optimizations:
  world:
    tileentitytick: false
  usercache: false
  cleanupreferences:
    player: false
    world: false
    
debug:
  #true for mode detailed logging (recommended)
  verbose: true
        
donottouch.configVersion: 0.1
