name: CarbonRenewed
main: io.github.lapisz.carbonrenewed.CarbonRenewed
version: 3.0.0
description: API for developers to add certain features to Spigot.
api-version: 1.16
load: STARTUP
authors: [Lapisz, Navid K., _Shevchik_, Aust1n46]
website: lapisz.github.io
softdepend: [ProtocolLib]
loadbefore: [LWC, NoCheatPlus, NoCheatPlusCompat]
commands:
  carbon:
    description: Carbon main command.
    usage: /<command> [argument]
